In [1]:
import pandas as pd

In [6]:
# submission_baseline_simple.csvを読み込む
df1 = pd.read_csv('../output/submission_baseline_simple.csv')

In [7]:
df1.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0.445699,0.445699,0.445699,0.445699,0.445699,0.490657,0.514748,0.457171,0.475547,...,0.464075,0.451456,0.469832,0.445699,0.445699,0.445699,0.445699,0.445699,0.445699,0.445699
1,HOBBIES_1_002_CA_1_validation,0.551482,0.551482,0.551482,0.551482,0.551482,0.596440,0.629507,0.562954,0.590306,...,0.578835,0.557239,0.584592,0.551482,0.551482,0.551482,0.551482,0.551482,0.551482,0.551482
2,HOBBIES_1_003_CA_1_validation,0.487881,0.487881,0.487881,0.487881,0.487881,0.547712,0.570103,0.499352,0.516029,...,0.504557,0.493638,0.510314,0.487881,0.487881,0.487881,0.487881,0.487881,0.487881,0.487881
3,HOBBIES_1_004_CA_1_validation,2.108566,2.108566,2.108566,2.108566,2.108566,2.153524,2.186591,2.120038,2.147390,...,2.135918,2.114323,2.141676,2.108566,2.108566,2.108566,2.108566,2.108566,2.108566,2.108566
4,HOBBIES_1_005_CA_1_validation,0.809711,0.809711,0.809711,0.809711,0.809711,0.828466,0.856566,0.821183,0.843569,...,0.832097,0.815468,0.837854,0.809711,0.809711,0.809711,0.809711,0.809711,0.809711,0.809711

In [8]:
# F1カラムを対象に0があるかチェック
df1[df1['F1'] < 0].head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
5717,FOODS_3_444_CA_2_validation,-0.736221,-0.736221,-0.736221,-0.736221,-0.736221,-0.222908,-0.105649,-0.439138,-0.570941,...,-0.868024,-0.688201,-0.820004,-0.736221,-0.736221,-0.736221,-0.736221,-0.736221,-0.736221,-0.736221
11054,FOODS_2_080_CA_4_validation,-0.238616,-0.238616,-0.238616,-0.238616,-0.238616,-0.193658,-0.015285,-0.169987,-0.008761,...,-0.077390,-0.187134,-0.025908,-0.238616,-0.238616,-0.238616,-0.238616,-0.238616,-0.238616,-0.238616
11576,FOODS_3_205_CA_4_validation,-0.099442,-0.099442,-0.099442,-0.099442,-0.099442,-0.059998,0.150570,0.098118,0.149012,...,-0.048547,-0.061556,-0.010661,-0.099442,-0.099442,-0.099442,-0.099442,-0.099442,-0.099442,-0.099442
11812,FOODS_3_441_CA_4_validation,-0.045720,-0.045720,-0.045720,-0.045720,-0.045720,0.532151,0.858974,0.214081,0.381230,...,0.121429,0.054407,0.221556,-0.045720,-0.045720,-0.045720,-0.045720,-0.045720,-0.045720,-0.045720
11815,FOODS_3_444_CA_4_validation,-0.713800,-0.713800,-0.713800,-0.713800,-0.713800,-0.200488,-0.200017,-0.364308,-0.612899,...,-0.962392,-0.613370,-0.861961,-0.713800,-0.713800,-0.713800,-0.713800,-0.713800,-0.713800,-0.713800

In [9]:
# submission_baseline.csvも確認
df2 = pd.read_csv('../output/submission_baseline.csv')

In [10]:
df2.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0.905495,0.827896,0.790424,0.795023,0.833223,0.982382,1.033127,0.881109,0.977788,...,0.914857,1.271746,1.076389,0.921096,0.881080,0.905859,0.991977,0.918808,1.097378,1.137098
1,HOBBIES_1_002_CA_1_validation,0.354463,0.320997,0.320997,0.301576,0.307628,0.357593,0.364888,0.244395,0.217398,...,0.225945,0.289272,0.293024,0.206939,0.178196,0.217932,0.202033,0.230001,0.300337,0.300337
2,HOBBIES_1_003_CA_1_validation,0.474119,0.461090,0.450940,0.450940,0.469370,0.551481,0.624160,0.383435,0.361015,...,0.548049,0.685132,0.843589,0.652712,0.642014,0.658159,0.595622,0.613185,0.785625,0.761913
3,HOBBIES_1_004_CA_1_validation,1.844888,1.735629,1.624588,1.474197,1.737930,1.866676,1.807172,1.436160,1.556543,...,1.797527,1.931331,2.203514,1.815092,1.674176,1.525150,1.561335,1.769712,2.550638,2.407861
4,HOBBIES_1_005_CA_1_validation,0.942016,0.799214,1.012675,1.107146,1.031846,1.369693,1.712780,1.223352,1.239845,...,1.101618,1.317522,1.297612,0.961924,0.964971,0.924828,0.984170,1.035614,1.323501,1.585699

In [11]:
# F1カラムを対象に0があるかチェック
df2[df2['F1'] < 0].head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
5346,FOODS_3_073_CA_2_validation,-0.004532,-0.010050,-0.010050,-0.010050,0.093652,0.185373,0.200903,0.025738,0.019221,...,0.125419,0.197592,0.196592,0.042946,0.019045,0.027972,0.020233,0.103958,0.170816,0.170816
20591,FOODS_3_073_TX_3_validation,-0.008013,-0.013531,-0.013531,-0.013531,0.090170,0.148869,0.164399,0.022257,0.015739,...,0.108217,0.172230,0.168785,0.000417,-0.026523,-0.017596,0.036983,0.120708,0.169465,0.169465